### PR TITLE
Add Cirru 0.0.1

### PR DESCRIPTION
**Pull request by jiyinyiyong**
https://github.com/Cirru/lt-cirru/releases/tag/0.0.1

image

### CODE REVIEW

**Comment by cldwalker** [comment]
Hi. I added your plugin with https://github.com/LightTable/plugin-metadata/commit/11cc0d320f0a58e4211cd196b99e8754eabadb8a since the directory needs to match the plugin name e.g. cirru -> cirru/0.0.1/

**Comment by jiyinyiyong** [comment]
Thanks. I thought you would prefer capitalized package names, I would update my `package.json` to match with that.

**Comment by cldwalker** [comment]
Ok. Once you update your plugin.edn to Cirru and repush your git tag, comment here and I can make the necessary changes

**Comment by jiyinyiyong** [comment]
That's cool. I just added a commit, hope I didn't make any mistake here:
https://github.com/Cirru/lt-cirru/commit/4c884fb7c6095bd6eb5bd0c6e77bb0c9376467f1
https://github.com/Cirru/lt-cirru/releases

`0.0.1` should be deprecated since I used `0.0.2` in this.

**Comment by cldwalker** [comment]
Updated

**Comment by jiyinyiyong** [comment]
Thanks :)

**Comment by kenny-evitt** [comment]
@jiyinyiyong Very nice!

**Comment by jiyinyiyong** [comment]
@kenny-evitt I've got another idea, would you like such a style(I mean highlighting the background, and the colors can be refined later)?
image

**Comment by kenny-evitt** [comment]
@jiyinyiyong I'm not familiar with Cirru beyond what I learned when I looked it up after seeing your plugin for it, so I can't really judge your highlighting technically. But in genetal I like nice semantic highlighting. Those colors tho are way too hot for my eyes.

**Comment by jiyinyiyong** [comment]
I made it working in Atom here, the colors should be better for reading:
https://discuss.atom.io/t/heres-how-i-style-language-cirru-in-0-1-5/23339

**Comment by kenny-evitt** [comment]
@jiyinyiyong That's a little easier on my eyes :smile:

**Pull request closed without merging**
